defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

executor_folder: logs_experiments
selected_experiments: []

slurm:
  timeout_min: 240
  partition: wzt_20250411,intel-sc3
  cpus_per_task: 8
  mem_per_cpu: 8GB
  mail_user: lizelun@westlake.edu.cn
  mail_type: BEGIN,END,FAIL
  qos: huge

experiments:
  demo_experiment:
    data_path:
      - /path/to/data_a.csv
      - /path/to/data_b.csv
    strategies: [HIGH_EXPRESSION, RANDOM]
    target_val_key: expressions
    regression_models: [LINEAR, RANDOM_FOREST]
    seeds: [1, 2]
    initial_sample_size: 8
    batch_size: 8
    test_size: 30
    max_rounds: 20
    normalize_expression: true
    normalize_input_output: true
    no_test: true
    output_dir: results/demo_experiment

hydra:
  run:
    dir: .
  output_subdir: null
