experiments:
  enformer_template:
    data_path: "/storage2/wangzitongLab/lizelun/project/gene_circuit_design/data/166k_Data/166k_rice/post_embeddings/all_embeddings_parallel_enformer_with_expressions.safetensors"  # Update with actual path
    strategies: ["HIGH_EXPRESSION", "RANDOM"]
    seq_mod_methods: ["EMBEDDING"]  # You'll need to implement this in sequence_utils.py
    regression_models: ["LINEAR", "KNN", "RANDOM_FOREST", "XGBOOST"]
    seeds: [1,2,3,4,5,6,7,8,9,10]
    initial_sample_size: 8
    batch_size: 8
    test_size: 30
    max_rounds: 20
    normalize_expression: true
    no_test: true
    output_dir: "results/enformer/enformer_10_second_round"

