# Active Learning Experiment Configurations
# Each configuration defines a complete experiment setup

experiments:

  # Basic embedding experiments with log likelihood
  embeddings_basic:
    data_path: "/Users/LZL/Desktop/Westlake_Research/gene_circuit_design/data/384_Data/embeddings/384_rice/post_embedding/combined_sequence_data_rank_0.csv"
    strategies: ["HIGH_EXPRESSION", "RANDOM", "LOG_LIKELIHOOD"]
    seq_mod_methods: ["EMBEDDING"]
    seeds: [42, 123, 456, 789, 999]
    initial_sample_size: 8
    batch_size: 8
    test_size: 50
    max_rounds: 20
    normalize_expression: false
    no_test: false
    output_dir: "results/results_all_strategies"

  # Embedding experiments with safetensors and normalization
  embeddings_normalized:
    data_path: "/Users/LZL/Desktop/Westlake_Research/gene_circuit_design/data/384_Data/embeddings/384_rice/post_embedding/combined_sequence_data_rank_0.safetensors"
    strategies: ["HIGH_EXPRESSION", "RANDOM", "LOG_LIKELIHOOD"]
    seq_mod_methods: ["EMBEDDING"]
    seeds: [42, 123, 456, 789, 999]
    initial_sample_size: 8
    batch_size: 8
    test_size: 30
    max_rounds: 20
    normalize_expression: true
    no_test: true
    output_dir: "results/results_all_strategies_evo2_embeddings_no_test_normalization"

  # Embedding experiments without normalization
  embeddings_no_norm:
    data_path: "/Users/LZL/Desktop/Westlake_Research/gene_circuit_design/data/384_Data/embeddings/384_rice/post_embedding/combined_sequence_data_rank_0.safetensors"
    strategies: ["HIGH_EXPRESSION", "RANDOM", "LOG_LIKELIHOOD"]
    seq_mod_methods: ["EMBEDDING"]
    seeds: [42, 123, 456, 789, 999]
    initial_sample_size: 8
    batch_size: 8
    test_size: 30
    max_rounds: 20
    normalize_expression: false
    no_test: true
    output_dir: "results/results_all_strategies_evo2_embeddings_no_test"

  # Trim and Pad sequence experiments
  trim_pad_basic:
    data_path: "/Users/LZL/Desktop/Westlake_Research/gene_circuit_design/data/384_Data/combined_sequence_data.csv"
    strategies: ["HIGH_EXPRESSION", "RANDOM", "LOG_LIKELIHOOD"]
    seq_mod_methods: ["TRIM", "PAD"]
    seeds: [42, 123, 456, 789, 999]
    initial_sample_size: 8
    batch_size: 8
    test_size: 30
    max_rounds: 20
    normalize_expression: false
    no_test: true
    output_dir: "results/results_all_strategies_ori_log_likelihood_pad_no_test"

  # CAR-based sequence modification
  car_experiments:
    data_path: "/Users/LZL/Desktop/Westlake_Research/gene_circuit_design/data/car_data/science.abq0225_data_s1.csv"
    strategies: ["HIGH_EXPRESSION", "RANDOM"]
    seq_mod_methods: ["CAR"]
    seeds: [42, 123, 456, 789, 999]
    initial_sample_size: 8
    batch_size: 8
    test_size: 30
    max_rounds: 20
    normalize_expression: false
    no_test: true
    output_dir: "results/results_all_strategies_CAR_no_test_no_normalization"

  # Current active experiment (ori log likelihood with embeddings)
  current_active:
    data_path: "/Users/LZL/Desktop/Westlake_Research/gene_circuit_design/data/384_Data/embeddings/384_rice/post_embedding/combined_sequence_data_rank_0_ori_log_likelihood.safetensors"
    strategies: ["HIGH_EXPRESSION", "RANDOM", "LOG_LIKELIHOOD"]
    seq_mod_methods: ["EMBEDDING"]
    seeds: [42, 123, 456, 789, 999]
    initial_sample_size: 8
    batch_size: 8
    test_size: 30
    max_rounds: 20
    normalize_expression: false
    no_test: true
    output_dir: "results/results_all_strategies_ori_log_likelihood_embeddings_no_test_normalization"

# Default experiment settings (can be overridden)
defaults:
  initial_sample_size: 8
  batch_size: 8
  test_size: 30
  max_rounds: 20
  normalize_expression: false
  no_test: true
  seeds: [42, 123, 456, 789, 999]
  strategies: ["HIGH_EXPRESSION", "RANDOM"]

# Available options for reference
options:
  strategies:
    - "HIGH_EXPRESSION"
    - "RANDOM"
    - "LOG_LIKELIHOOD"
    - "UNCERTAINTY"

  seq_mod_methods:
    - "TRIM"
    - "PAD"
    - "EMBEDDING"
    - "CAR"
