experiments:
  # 1. Pre-computed PCA results (from one-hot encoding)
  onehot_pca_experiment:
    data_path: "data/166k_data/166k_rice/post_embeddings/pca_results_32cores.safetensors"
    strategies: ["HIGH_EXPRESSION", "RANDOM", "LOG_LIKELIHOOD"]
    seq_mod_methods: ["EMBEDDING"]  # Use EMBEDDING to load pre-computed PCA from safetensors
    regression_models: ["LINEAR", "KNN", "RANDOM_FOREST"]
    seeds: [42, 123]
    initial_sample_size: 8
    batch_size: 8
    test_size: 30
    max_rounds: 5
    normalize_expression: true
    no_test: true
    # use_pca: true  # Remove this since PCA is already applied
    # pca_components: 4096  # Remove this since PCA is already applied
    output_dir: "results/final_test/onehot_pca"
    cores_per_process: 4

  # 2. Embedding-based experiments with 10 replicates
  evo_embeddings_replicates:
    data_path: "data/166k_data/166k_rice/post_embeddings/all_tensor_data.safetensors"
    strategies: ["HIGH_EXPRESSION", "RANDOM", "LOG_LIKELIHOOD"]
    seq_mod_methods: ["EMBEDDING"]
    regression_models: ["LINEAR", "KNN", "RANDOM_FOREST"]
    seeds: [42, 123]
    initial_sample_size: 8
    batch_size: 8
    test_size: 30
    max_rounds: 5
    normalize_expression: true
    no_test: true
    output_dir: "results/final_test/evo_embeddings_replicates"
    cores_per_process: 4

  # 3. Enformer template (to be filled in later)
  # enformer_template:
  #   data_path: "data/enformer_data/enformer_embeddings.csv"  # Update with actual path
  #   strategies: ["HIGH_EXPRESSION", "RANDOM", "LOG_LIKELIHOOD"]
  #   seq_mod_methods: ["ENFORMER"]  # You'll need to implement this in sequence_utils.py
  #   regression_models: ["LINEAR", "KNN", "RANDOM_FOREST"]
  #   seeds: [42, 123, 456, 789, 999, 101, 202, 303, 404, 505]
  #   initial_sample_size: 8
  #   batch_size: 8
  #   test_size: 30
  #   max_rounds: 3
  #   normalize_expression: true
  #   no_test: true
  #   # enformer_model_path: "path/to/enformer/model"  # Add if needed
  #   # enformer_embedding_dim: 3072  # Add if needed
  #   output_dir: "results/final_test/enformer"
