experiments:
  onehot_pad:
    data_path: "/storage2/wangzitongLab/lizelun/project/gene_circuit_design/data/166k_Data/166k_rice/post_embeddings/all_data_with_sequence.csv"
    strategies: ["HIGH_EXPRESSION", "RANDOM", "LOG_LIKELIHOOD"]
    seq_mod_methods: ["PAD"]
    seeds: [42, 123]
    initial_sample_size: 8
    batch_size: 8
    test_size: 30
    max_rounds: 20
    normalize_expression: false
    no_test: true
    output_dir: "results/onehot_pad/5_seeds_test"