# job_sub/conf/transforms/log_standardize.yaml
steps:
  - id: log1p
    _target_: sklearn.preprocessing.FunctionTransformer
    func:
      _target_: hydra.utils.get_method
      path: numpy.log1p
    inverse_func:
      _target_: hydra.utils.get_method
      path: numpy.expm1
  - id: scaler
    _target_: sklearn.preprocessing.StandardScaler
